apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - postgres-configmap.yml
    - postgres-storage.yml
    - postgres-deploy.yml
    - postgres-service.yml

namespace: postgres

commonLabels:
    env: dev
